version: "2"
linters:
  default: all
  disable:
    - wsl
    - exhaustruct # Disallows to leave unused fields in structs
    - depguard # Exhausting
    - ireturn # Disallows to return Interfaces
    - wrapcheck # Disallows to use non-wrapped errors
    - gochecknoinits # Disallows to use init functions
    - perfsprint
    - gochecknoglobals
    - funlen
    - revive
    - noinlineerr
  settings:
    cyclop:
      max-complexity: 12
    varnamelen:
      min-name-length: 1
    wsl_v5:
      allow-first-in-block: true
      allow-whole-block: false
      branch-max-lines: 2
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
run:
  go: "1.26"
  tests: false
