dir: mocks/{{ replaceAll "internal" "internal_" .SrcPackagePath }}
template: testify
filename: mock_{{ .InterfaceName }}.go
packages:
  sigs.k8s.io/controller-runtime/pkg/cache:
    interfaces:
      Cache:
  sigs.k8s.io/controller-runtime/pkg/client:
    interfaces:
      Client:
  sigs.k8s.io/controller-runtime/pkg/manager:
    interfaces:
      Manager:
  github.com/NCCloud/metadata-reflector/internal/clients:
    interfaces:
      KubernetesClient:
