// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package client

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"k8s.io/apimachinery/pkg/api/meta"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockClient
func (_mock *MockClient) Create(ctx context.Context, obj client.Object, opts ...client.CreateOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, ...client.CreateOption) error); ok {
		r0 = returnFunc(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - obj
//   - opts
func (_e *MockClient_Expecter) Create(ctx interface{}, obj interface{}, opts ...interface{}) *MockClient_Create_Call {
	return &MockClient_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *MockClient_Create_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.CreateOption)) *MockClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]client.CreateOption)
		run(args[0].(context.Context), args[1].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Create_Call) Return(err error) *MockClient_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Create_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, opts ...client.CreateOption) error) *MockClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockClient
func (_mock *MockClient) Delete(ctx context.Context, obj client.Object, opts ...client.DeleteOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, ...client.DeleteOption) error); ok {
		r0 = returnFunc(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx
//   - obj
//   - opts
func (_e *MockClient_Expecter) Delete(ctx interface{}, obj interface{}, opts ...interface{}) *MockClient_Delete_Call {
	return &MockClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *MockClient_Delete_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.DeleteOption)) *MockClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]client.DeleteOption)
		run(args[0].(context.Context), args[1].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Delete_Call) Return(err error) *MockClient_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Delete_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, opts ...client.DeleteOption) error) *MockClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllOf provides a mock function for the type MockClient
func (_mock *MockClient) DeleteAllOf(ctx context.Context, obj client.Object, opts ...client.DeleteAllOfOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllOf")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, ...client.DeleteAllOfOption) error); ok {
		r0 = returnFunc(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteAllOf_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllOf'
type MockClient_DeleteAllOf_Call struct {
	*mock.Call
}

// DeleteAllOf is a helper method to define mock.On call
//   - ctx
//   - obj
//   - opts
func (_e *MockClient_Expecter) DeleteAllOf(ctx interface{}, obj interface{}, opts ...interface{}) *MockClient_DeleteAllOf_Call {
	return &MockClient_DeleteAllOf_Call{Call: _e.mock.On("DeleteAllOf",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *MockClient_DeleteAllOf_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.DeleteAllOfOption)) *MockClient_DeleteAllOf_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]client.DeleteAllOfOption)
		run(args[0].(context.Context), args[1].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_DeleteAllOf_Call) Return(err error) *MockClient_DeleteAllOf_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteAllOf_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, opts ...client.DeleteAllOfOption) error) *MockClient_DeleteAllOf_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockClient
func (_mock *MockClient) Get(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, key, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, key, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ObjectKey, client.Object, ...client.GetOption) error); ok {
		r0 = returnFunc(ctx, key, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - key
//   - obj
//   - opts
func (_e *MockClient_Expecter) Get(ctx interface{}, key interface{}, obj interface{}, opts ...interface{}) *MockClient_Get_Call {
	return &MockClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, key, obj}, opts...)...)}
}

func (_c *MockClient_Get_Call) Run(run func(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption)) *MockClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[3].([]client.GetOption)
		run(args[0].(context.Context), args[1].(client.ObjectKey), args[2].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Get_Call) Return(err error) *MockClient_Get_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Get_Call) RunAndReturn(run func(ctx context.Context, key client.ObjectKey, obj client.Object, opts ...client.GetOption) error) *MockClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GroupVersionKindFor provides a mock function for the type MockClient
func (_mock *MockClient) GroupVersionKindFor(obj runtime.Object) (schema.GroupVersionKind, error) {
	ret := _mock.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for GroupVersionKindFor")
	}

	var r0 schema.GroupVersionKind
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(runtime.Object) (schema.GroupVersionKind, error)); ok {
		return returnFunc(obj)
	}
	if returnFunc, ok := ret.Get(0).(func(runtime.Object) schema.GroupVersionKind); ok {
		r0 = returnFunc(obj)
	} else {
		r0 = ret.Get(0).(schema.GroupVersionKind)
	}
	if returnFunc, ok := ret.Get(1).(func(runtime.Object) error); ok {
		r1 = returnFunc(obj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GroupVersionKindFor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GroupVersionKindFor'
type MockClient_GroupVersionKindFor_Call struct {
	*mock.Call
}

// GroupVersionKindFor is a helper method to define mock.On call
//   - obj
func (_e *MockClient_Expecter) GroupVersionKindFor(obj interface{}) *MockClient_GroupVersionKindFor_Call {
	return &MockClient_GroupVersionKindFor_Call{Call: _e.mock.On("GroupVersionKindFor", obj)}
}

func (_c *MockClient_GroupVersionKindFor_Call) Run(run func(obj runtime.Object)) *MockClient_GroupVersionKindFor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(runtime.Object))
	})
	return _c
}

func (_c *MockClient_GroupVersionKindFor_Call) Return(groupVersionKind schema.GroupVersionKind, err error) *MockClient_GroupVersionKindFor_Call {
	_c.Call.Return(groupVersionKind, err)
	return _c
}

func (_c *MockClient_GroupVersionKindFor_Call) RunAndReturn(run func(obj runtime.Object) (schema.GroupVersionKind, error)) *MockClient_GroupVersionKindFor_Call {
	_c.Call.Return(run)
	return _c
}

// IsObjectNamespaced provides a mock function for the type MockClient
func (_mock *MockClient) IsObjectNamespaced(obj runtime.Object) (bool, error) {
	ret := _mock.Called(obj)

	if len(ret) == 0 {
		panic("no return value specified for IsObjectNamespaced")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(runtime.Object) (bool, error)); ok {
		return returnFunc(obj)
	}
	if returnFunc, ok := ret.Get(0).(func(runtime.Object) bool); ok {
		r0 = returnFunc(obj)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(runtime.Object) error); ok {
		r1 = returnFunc(obj)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_IsObjectNamespaced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsObjectNamespaced'
type MockClient_IsObjectNamespaced_Call struct {
	*mock.Call
}

// IsObjectNamespaced is a helper method to define mock.On call
//   - obj
func (_e *MockClient_Expecter) IsObjectNamespaced(obj interface{}) *MockClient_IsObjectNamespaced_Call {
	return &MockClient_IsObjectNamespaced_Call{Call: _e.mock.On("IsObjectNamespaced", obj)}
}

func (_c *MockClient_IsObjectNamespaced_Call) Run(run func(obj runtime.Object)) *MockClient_IsObjectNamespaced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(runtime.Object))
	})
	return _c
}

func (_c *MockClient_IsObjectNamespaced_Call) Return(b bool, err error) *MockClient_IsObjectNamespaced_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockClient_IsObjectNamespaced_Call) RunAndReturn(run func(obj runtime.Object) (bool, error)) *MockClient_IsObjectNamespaced_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockClient
func (_mock *MockClient) List(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, list, opts)
	} else {
		tmpRet = _mock.Called(ctx, list)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.ObjectList, ...client.ListOption) error); ok {
		r0 = returnFunc(ctx, list, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockClient_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx
//   - list
//   - opts
func (_e *MockClient_Expecter) List(ctx interface{}, list interface{}, opts ...interface{}) *MockClient_List_Call {
	return &MockClient_List_Call{Call: _e.mock.On("List",
		append([]interface{}{ctx, list}, opts...)...)}
}

func (_c *MockClient_List_Call) Run(run func(ctx context.Context, list client.ObjectList, opts ...client.ListOption)) *MockClient_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]client.ListOption)
		run(args[0].(context.Context), args[1].(client.ObjectList), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_List_Call) Return(err error) *MockClient_List_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_List_Call) RunAndReturn(run func(ctx context.Context, list client.ObjectList, opts ...client.ListOption) error) *MockClient_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function for the type MockClient
func (_mock *MockClient) Patch(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.PatchOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, patch, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj, patch)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, client.Patch, ...client.PatchOption) error); ok {
		r0 = returnFunc(ctx, obj, patch, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type MockClient_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx
//   - obj
//   - patch
//   - opts
func (_e *MockClient_Expecter) Patch(ctx interface{}, obj interface{}, patch interface{}, opts ...interface{}) *MockClient_Patch_Call {
	return &MockClient_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, obj, patch}, opts...)...)}
}

func (_c *MockClient_Patch_Call) Run(run func(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.PatchOption)) *MockClient_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[3].([]client.PatchOption)
		run(args[0].(context.Context), args[1].(client.Object), args[2].(client.Patch), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Patch_Call) Return(err error) *MockClient_Patch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Patch_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, patch client.Patch, opts ...client.PatchOption) error) *MockClient_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// RESTMapper provides a mock function for the type MockClient
func (_mock *MockClient) RESTMapper() meta.RESTMapper {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RESTMapper")
	}

	var r0 meta.RESTMapper
	if returnFunc, ok := ret.Get(0).(func() meta.RESTMapper); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(meta.RESTMapper)
		}
	}
	return r0
}

// MockClient_RESTMapper_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RESTMapper'
type MockClient_RESTMapper_Call struct {
	*mock.Call
}

// RESTMapper is a helper method to define mock.On call
func (_e *MockClient_Expecter) RESTMapper() *MockClient_RESTMapper_Call {
	return &MockClient_RESTMapper_Call{Call: _e.mock.On("RESTMapper")}
}

func (_c *MockClient_RESTMapper_Call) Run(run func()) *MockClient_RESTMapper_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_RESTMapper_Call) Return(rESTMapper meta.RESTMapper) *MockClient_RESTMapper_Call {
	_c.Call.Return(rESTMapper)
	return _c
}

func (_c *MockClient_RESTMapper_Call) RunAndReturn(run func() meta.RESTMapper) *MockClient_RESTMapper_Call {
	_c.Call.Return(run)
	return _c
}

// Scheme provides a mock function for the type MockClient
func (_mock *MockClient) Scheme() *runtime.Scheme {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Scheme")
	}

	var r0 *runtime.Scheme
	if returnFunc, ok := ret.Get(0).(func() *runtime.Scheme); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*runtime.Scheme)
		}
	}
	return r0
}

// MockClient_Scheme_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scheme'
type MockClient_Scheme_Call struct {
	*mock.Call
}

// Scheme is a helper method to define mock.On call
func (_e *MockClient_Expecter) Scheme() *MockClient_Scheme_Call {
	return &MockClient_Scheme_Call{Call: _e.mock.On("Scheme")}
}

func (_c *MockClient_Scheme_Call) Run(run func()) *MockClient_Scheme_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Scheme_Call) Return(scheme *runtime.Scheme) *MockClient_Scheme_Call {
	_c.Call.Return(scheme)
	return _c
}

func (_c *MockClient_Scheme_Call) RunAndReturn(run func() *runtime.Scheme) *MockClient_Scheme_Call {
	_c.Call.Return(run)
	return _c
}

// Status provides a mock function for the type MockClient
func (_mock *MockClient) Status() client.SubResourceWriter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 client.SubResourceWriter
	if returnFunc, ok := ret.Get(0).(func() client.SubResourceWriter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SubResourceWriter)
		}
	}
	return r0
}

// MockClient_Status_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Status'
type MockClient_Status_Call struct {
	*mock.Call
}

// Status is a helper method to define mock.On call
func (_e *MockClient_Expecter) Status() *MockClient_Status_Call {
	return &MockClient_Status_Call{Call: _e.mock.On("Status")}
}

func (_c *MockClient_Status_Call) Run(run func()) *MockClient_Status_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockClient_Status_Call) Return(subResourceWriter client.SubResourceWriter) *MockClient_Status_Call {
	_c.Call.Return(subResourceWriter)
	return _c
}

func (_c *MockClient_Status_Call) RunAndReturn(run func() client.SubResourceWriter) *MockClient_Status_Call {
	_c.Call.Return(run)
	return _c
}

// SubResource provides a mock function for the type MockClient
func (_mock *MockClient) SubResource(subResource string) client.SubResourceClient {
	ret := _mock.Called(subResource)

	if len(ret) == 0 {
		panic("no return value specified for SubResource")
	}

	var r0 client.SubResourceClient
	if returnFunc, ok := ret.Get(0).(func(string) client.SubResourceClient); ok {
		r0 = returnFunc(subResource)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.SubResourceClient)
		}
	}
	return r0
}

// MockClient_SubResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SubResource'
type MockClient_SubResource_Call struct {
	*mock.Call
}

// SubResource is a helper method to define mock.On call
//   - subResource
func (_e *MockClient_Expecter) SubResource(subResource interface{}) *MockClient_SubResource_Call {
	return &MockClient_SubResource_Call{Call: _e.mock.On("SubResource", subResource)}
}

func (_c *MockClient_SubResource_Call) Run(run func(subResource string)) *MockClient_SubResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockClient_SubResource_Call) Return(subResourceClient client.SubResourceClient) *MockClient_SubResource_Call {
	_c.Call.Return(subResourceClient)
	return _c
}

func (_c *MockClient_SubResource_Call) RunAndReturn(run func(subResource string) client.SubResourceClient) *MockClient_SubResource_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockClient
func (_mock *MockClient) Update(ctx context.Context, obj client.Object, opts ...client.UpdateOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, obj, opts)
	} else {
		tmpRet = _mock.Called(ctx, obj)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, client.Object, ...client.UpdateOption) error); ok {
		r0 = returnFunc(ctx, obj, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx
//   - obj
//   - opts
func (_e *MockClient_Expecter) Update(ctx interface{}, obj interface{}, opts ...interface{}) *MockClient_Update_Call {
	return &MockClient_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, obj}, opts...)...)}
}

func (_c *MockClient_Update_Call) Run(run func(ctx context.Context, obj client.Object, opts ...client.UpdateOption)) *MockClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[2].([]client.UpdateOption)
		run(args[0].(context.Context), args[1].(client.Object), variadicArgs...)
	})
	return _c
}

func (_c *MockClient_Update_Call) Return(err error) *MockClient_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_Update_Call) RunAndReturn(run func(ctx context.Context, obj client.Object, opts ...client.UpdateOption) error) *MockClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
