// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package clients

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/api/apps/v1"
	v10 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/types"
)

// NewMockKubernetesClient creates a new instance of MockKubernetesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKubernetesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKubernetesClient {
	mock := &MockKubernetesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockKubernetesClient is an autogenerated mock type for the KubernetesClient type
type MockKubernetesClient struct {
	mock.Mock
}

type MockKubernetesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockKubernetesClient) EXPECT() *MockKubernetesClient_Expecter {
	return &MockKubernetesClient_Expecter{mock: &_m.Mock}
}

// GetDeployment provides a mock function for the type MockKubernetesClient
func (_mock *MockKubernetesClient) GetDeployment(ctx context.Context, namespacedName types.NamespacedName) (*v1.Deployment, error) {
	ret := _mock.Called(ctx, namespacedName)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployment")
	}

	var r0 *v1.Deployment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName) (*v1.Deployment, error)); ok {
		return returnFunc(ctx, namespacedName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.NamespacedName) *v1.Deployment); ok {
		r0 = returnFunc(ctx, namespacedName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Deployment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.NamespacedName) error); ok {
		r1 = returnFunc(ctx, namespacedName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubernetesClient_GetDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeployment'
type MockKubernetesClient_GetDeployment_Call struct {
	*mock.Call
}

// GetDeployment is a helper method to define mock.On call
//   - ctx
//   - namespacedName
func (_e *MockKubernetesClient_Expecter) GetDeployment(ctx interface{}, namespacedName interface{}) *MockKubernetesClient_GetDeployment_Call {
	return &MockKubernetesClient_GetDeployment_Call{Call: _e.mock.On("GetDeployment", ctx, namespacedName)}
}

func (_c *MockKubernetesClient_GetDeployment_Call) Run(run func(ctx context.Context, namespacedName types.NamespacedName)) *MockKubernetesClient_GetDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(types.NamespacedName))
	})
	return _c
}

func (_c *MockKubernetesClient_GetDeployment_Call) Return(deployment *v1.Deployment, err error) *MockKubernetesClient_GetDeployment_Call {
	_c.Call.Return(deployment, err)
	return _c
}

func (_c *MockKubernetesClient_GetDeployment_Call) RunAndReturn(run func(ctx context.Context, namespacedName types.NamespacedName) (*v1.Deployment, error)) *MockKubernetesClient_GetDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeployments provides a mock function for the type MockKubernetesClient
func (_mock *MockKubernetesClient) ListDeployments(ctx context.Context, labelSelector labels.Selector) (*v1.DeploymentList, error) {
	ret := _mock.Called(ctx, labelSelector)

	if len(ret) == 0 {
		panic("no return value specified for ListDeployments")
	}

	var r0 *v1.DeploymentList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, labels.Selector) (*v1.DeploymentList, error)); ok {
		return returnFunc(ctx, labelSelector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, labels.Selector) *v1.DeploymentList); ok {
		r0 = returnFunc(ctx, labelSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.DeploymentList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, labels.Selector) error); ok {
		r1 = returnFunc(ctx, labelSelector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubernetesClient_ListDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeployments'
type MockKubernetesClient_ListDeployments_Call struct {
	*mock.Call
}

// ListDeployments is a helper method to define mock.On call
//   - ctx
//   - labelSelector
func (_e *MockKubernetesClient_Expecter) ListDeployments(ctx interface{}, labelSelector interface{}) *MockKubernetesClient_ListDeployments_Call {
	return &MockKubernetesClient_ListDeployments_Call{Call: _e.mock.On("ListDeployments", ctx, labelSelector)}
}

func (_c *MockKubernetesClient_ListDeployments_Call) Run(run func(ctx context.Context, labelSelector labels.Selector)) *MockKubernetesClient_ListDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(labels.Selector))
	})
	return _c
}

func (_c *MockKubernetesClient_ListDeployments_Call) Return(deploymentList *v1.DeploymentList, err error) *MockKubernetesClient_ListDeployments_Call {
	_c.Call.Return(deploymentList, err)
	return _c
}

func (_c *MockKubernetesClient_ListDeployments_Call) RunAndReturn(run func(ctx context.Context, labelSelector labels.Selector) (*v1.DeploymentList, error)) *MockKubernetesClient_ListDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// ListPods provides a mock function for the type MockKubernetesClient
func (_mock *MockKubernetesClient) ListPods(ctx context.Context, labelSelector labels.Selector) (*v10.PodList, error) {
	ret := _mock.Called(ctx, labelSelector)

	if len(ret) == 0 {
		panic("no return value specified for ListPods")
	}

	var r0 *v10.PodList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, labels.Selector) (*v10.PodList, error)); ok {
		return returnFunc(ctx, labelSelector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, labels.Selector) *v10.PodList); ok {
		r0 = returnFunc(ctx, labelSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v10.PodList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, labels.Selector) error); ok {
		r1 = returnFunc(ctx, labelSelector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockKubernetesClient_ListPods_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPods'
type MockKubernetesClient_ListPods_Call struct {
	*mock.Call
}

// ListPods is a helper method to define mock.On call
//   - ctx
//   - labelSelector
func (_e *MockKubernetesClient_Expecter) ListPods(ctx interface{}, labelSelector interface{}) *MockKubernetesClient_ListPods_Call {
	return &MockKubernetesClient_ListPods_Call{Call: _e.mock.On("ListPods", ctx, labelSelector)}
}

func (_c *MockKubernetesClient_ListPods_Call) Run(run func(ctx context.Context, labelSelector labels.Selector)) *MockKubernetesClient_ListPods_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(labels.Selector))
	})
	return _c
}

func (_c *MockKubernetesClient_ListPods_Call) Return(podList *v10.PodList, err error) *MockKubernetesClient_ListPods_Call {
	_c.Call.Return(podList, err)
	return _c
}

func (_c *MockKubernetesClient_ListPods_Call) RunAndReturn(run func(ctx context.Context, labelSelector labels.Selector) (*v10.PodList, error)) *MockKubernetesClient_ListPods_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePod provides a mock function for the type MockKubernetesClient
func (_mock *MockKubernetesClient) UpdatePod(ctx context.Context, pod v10.Pod) error {
	ret := _mock.Called(ctx, pod)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePod")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, v10.Pod) error); ok {
		r0 = returnFunc(ctx, pod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockKubernetesClient_UpdatePod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePod'
type MockKubernetesClient_UpdatePod_Call struct {
	*mock.Call
}

// UpdatePod is a helper method to define mock.On call
//   - ctx
//   - pod
func (_e *MockKubernetesClient_Expecter) UpdatePod(ctx interface{}, pod interface{}) *MockKubernetesClient_UpdatePod_Call {
	return &MockKubernetesClient_UpdatePod_Call{Call: _e.mock.On("UpdatePod", ctx, pod)}
}

func (_c *MockKubernetesClient_UpdatePod_Call) Run(run func(ctx context.Context, pod v10.Pod)) *MockKubernetesClient_UpdatePod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v10.Pod))
	})
	return _c
}

func (_c *MockKubernetesClient_UpdatePod_Call) Return(err error) *MockKubernetesClient_UpdatePod_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockKubernetesClient_UpdatePod_Call) RunAndReturn(run func(ctx context.Context, pod v10.Pod) error) *MockKubernetesClient_UpdatePod_Call {
	_c.Call.Return(run)
	return _c
}
